spring:
  datasource:
    url: jdbc:mysql://localhost:3306/suhsportdb?useSSL=false
    username: root
    password: 1320mySQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect